name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh
  - asyncssh
  - dask
  - dask-ml
  - jupyterlab<3 # Workspace layouts are broken in 3.0. Should be fixed in 3.1.
  - ipykernel
  - ipywidgets
  - nodejs
  - tornado
  - numba
  - numpy
  - pip
  - pandas
  - pyarrow
  - python-graphviz
  - seaborn
  - scikit-learn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - requests
  - pytables
  - pip:
      - mimesis
      - dask_labextension
